import turtle
t = turtle.Turtle()
t.speed(15)
def draw_rectangle(length, width, color):
    t.fillcolor(color)
    t.begin_fill()
    for i in range(2):
        t.forward(length)
        t.right(90)
        t.forward(width)
        t.right(90)
    t.end_fill()
draw_rectangle(300, 100, "orange")
t.penup()
t.goto(0, -100)
t.pendown()
draw_rectangle(300, 100, "white")
t.penup()
t.goto(0, -200)
t.pendown()
draw_rectangle(300, 100, "green")
t.penup()
t.goto(150, -150)
t.pendown()
t.color("blue")
t.circle(50)
for i in range(24):
    t.penup()
    t.goto(150, -100)
    t.pendown()
    t.setheading(i * 15)
    t.forward(50)
t.hideturtle()
turtle.done()
